services:
  worker:
    build: ./worker
    deploy:
      mode: replicated
      replicas: ${WORKERS_COUNT}
  manager:
    build: ./manager
    ports:
      - "8000:8000"
    environment:
      - WORKERS_COUNT=${WORKERS_COUNT}
